# Generated by Django 5.2.10 on 2026-01-27 11:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.IntegerField(db_index=True, help_text='Identifier to group legs of the same snapshot', unique=True)),
                ('name', models.CharField(help_text='Snapshot name or description', max_length=200, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.CharField(blank=True, help_text='Free form description of the snapshot', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Stock or instrument ticker symbol', max_length=100)),
                ('date', models.DateField(help_text='Date when the snapshot was taken')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at which the snapshot was entered', max_digits=10)),
                ('quantity', models.IntegerField(help_text='Number of shares/contracts (negative for short positions)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.ForeignKey(db_column='snapshot_id', help_text='Foreign key to the parent snapshot', on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='snapshot.snapshot', to_field='snapshot_id')),
            ],
            options={
                'verbose_name': 'Snapshot Leg',
                'verbose_name_plural': 'Snapshot Legs',
                'ordering': ['snapshot', '-date'],
                'indexes': [models.Index(fields=['snapshot'], name='snapshot_sn_snapsho_377439_idx'), models.Index(fields=['date'], name='snapshot_sn_date_1c1131_idx')],
            },
        ),
    ]
