# Generated by Django 4.2.27 on 2026-01-21 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.IntegerField(db_index=True, help_text='Identifier to group legs of the same trade')),
                ('name', models.CharField(help_text='Trade name or description', max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('is_open', models.BooleanField(default=True, help_text='Whether this leg is still open')),
                ('ticker', models.CharField(help_text='Stock or instrument ticker symbol', max_length=20)),
                ('entry_date', models.DateField(help_text='Date when the position was entered')),
                ('exit_date', models.DateField(blank=True, help_text='Date when the position was exited (null if still open)', null=True)),
                ('entry_price', models.DecimalField(decimal_places=2, help_text='Price at which the position was entered', max_digits=12)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price at which the position was exited (null if still open)', max_digits=12, null=True)),
                ('quantity', models.IntegerField(help_text='Number of shares/contracts (negative for short positions)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trade Leg',
                'verbose_name_plural': 'Trade Legs',
                'ordering': ['trade_id', '-entry_date'],
                'indexes': [models.Index(fields=['trade_id', 'is_open'], name='trades_trad_trade_i_23933b_idx'), models.Index(fields=['entry_date'], name='trades_trad_entry_d_572fd5_idx')],
            },
        ),
    ]
