# Generated by Django 5.2.10 on 2026-01-24 11:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.IntegerField(db_index=True, help_text='Identifier to group legs of the same trade', unique=True)),
                ('name', models.CharField(help_text='Trade name or description', max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.CharField(blank=True, help_text='Free form description of the trade', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Stock or instrument ticker symbol', max_length=20)),
                ('entry_date', models.DateField(help_text='Date when the position was entered')),
                ('exit_date', models.DateField(blank=True, help_text='Date when the position was exited (null if still open)', null=True)),
                ('entry_price', models.DecimalField(decimal_places=2, help_text='Price at which the position was entered', max_digits=12)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price at which the position was exited (null if still open)', max_digits=12, null=True)),
                ('quantity', models.IntegerField(help_text='Number of shares/contracts (negative for short positions)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.ForeignKey(db_column='trade_id', help_text='Foreign key to the parent trade', on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='trade.trade', to_field='trade_id')),
            ],
            options={
                'verbose_name': 'Trade Leg',
                'verbose_name_plural': 'Trade Legs',
                'ordering': ['trade', '-entry_date'],
                'indexes': [models.Index(fields=['trade'], name='trade_trade_trade_i_6ff6b2_idx'), models.Index(fields=['entry_date'], name='trade_trade_entry_d_c67418_idx')],
            },
        ),
    ]
