# Generated by Django 5.2.10 on 2026-01-27 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='name',
            field=models.CharField(help_text='Trade name or description', max_length=200, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tradeleg',
            name='entry_price',
            field=models.DecimalField(decimal_places=2, help_text='Price at which the position was entered', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tradeleg',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at which the position was exited (null if still open)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradeleg',
            name='ticker',
            field=models.CharField(help_text='Stock or instrument ticker symbol', max_length=100),
        ),
    ]
