# Generated by Django 5.2.10 on 2026-01-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FyersMasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_symbol', models.CharField(db_index=True, max_length=100, unique=True)),
                ('underlying_symbol', models.CharField(db_index=True, max_length=50)),
                ('expiry_epoch', models.BigIntegerField(blank=True, null=True)),
                ('expiry_epoch_dup', models.CharField(blank=True, max_length=50, null=True)),
                ('symbol_details', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fyers Master Data',
                'verbose_name_plural': 'Fyers Master Data Records',
            },
        ),
        migrations.CreateModel(
            name='FyersToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fyers Token',
                'verbose_name_plural': 'Fyers Tokens',
            },
        ),
    ]
