# Generated by Django 5.2.10 on 2026-01-27 08:14

from django.db import migrations


def copy_configuration_to_common(apps, schema_editor):
    """Copy configuration data from brokers.Configuration to common.Configuration"""
    BrokersConfiguration = apps.get_model('brokers', 'Configuration')
    CommonConfiguration = apps.get_model('common', 'Configuration')
    
    # Copy all configuration records
    for config in BrokersConfiguration.objects.all():
        CommonConfiguration.objects.update_or_create(
            key=config.key,
            defaults={
                'value': config.value,
                'created_at': config.created_at,
                'updated_at': config.updated_at,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_configuration_delete_fyerstoken'),
        ('common', '0001_initial'),  # Ensure common.Configuration exists
    ]

    operations = [
        migrations.RunPython(copy_configuration_to_common, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
